server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            # ¡OJO! ${segment} debe ir escapado como $\{segment}
            - RewritePath=/users/(?<segment>.*), /api/users/$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

