server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # AUTH -> /auth/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        # USERS -> /users/** (se reescribe a /api/users/** en el servicio)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            # IMPORTANTE: ${segment} DEBE IR ESCAPADO como $\{segment}
            - RewritePath=/users/(?<segment>.*), /api/users/$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
