# Compartido (aplica a todos los servicios)
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # agrega 'gateway' sólo en el gateway.yml
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Eureka (cliente) por defecto. El servidor (service-registry) lo sobreescribe.
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# JWT compartido (se puede sobreescribir con variable de entorno en prod)
auth:
  jwt:
    secret: ${AUTH_JWT_SECRET:dev-please-change-this-super-secret-256bit-key-1234567890}
    issuer: zillowmini-auth
