server:
  port: 9001

spring:
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
auth:
  jwt:
    secret: ${AUTH_JWT_SECRET:dev-please-change-this-super-secret-256bit-key-1234567890_ABCDEFGH_abcdefgh_1234567890}
    issuer: "zillowmini-auth"
    ttlMinutes: 60

management:
  endpoints:
    web:
      exposure:
        include: health,info
