server:
  port: 9002

spring:
  application:
    name: user-service
    datasource:
    url: jdbc:postgresql://localhost:5432/zillowmini_userdb
    username: postgres
    password: mpc
  jpa:
    hibernate:
      ddl-auto: validate   # Flyway controla el esquema
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    schemas: zillowmini_user
    baseline-on-migrate: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
auth:
  jwt:
    secret: ${AUTH_JWT_SECRET:dev-please-change-this-super-secret-256bit-key-1234567890_ABCDEFGH_abcdefgh_1234567890}


management:
  endpoints:
    web:
      exposure:
        include: health,info
